{% set name = "cassandra-driver" %}
{% set version = "3.29.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cassandra-driver-{{ version }}.tar.gz
  sha256: c4310a7d0457f51a63fb019d8ef501588c491141362b53097fbc62fa06559b7c

build:
  number: 2
  script: python setup.py build build_ext -I${PREFIX}/include -L${PREFIX}/lib install --single-version-externally-managed --record record.txt  # [not win]
  script: python setup.py install --no-cython --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=0.20,!=0.25,<0.30             # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython >=0.20,!=0.25,<0.30
    - libev  # [not win]

  run:
    - python
    - geomet >=0.1,<0.3
    - numpy
    - libev  # [not win]

test:
  requires:
    - pip
  imports:
    - cassandra
    - cassandra.cqlengine
    - cassandra.io
    - cassandra.numpy_parser  # [not win and python_impl == 'cpython']
  commands:
    - pip check

about:
  home: http://github.com/datastax/python-driver
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python driver for Cassandra
  description: |
    A modern, feature-rich and highly-tunable Python client library for Apache Cassandra (2.1+)
    using exclusively Cassandra’s binary protocol and Cassandra Query Language v3.
  doc_url: http://datastax.github.io/python-driver/api/index.html
  dev_url: http://github.com/datastax/python-driver

extra:
  recipe-maintainers:
    - petercable
    - anirrudh
    - scopatz
    - xylar
