{% set name = "cassandra-driver" %}
{% set version = "3.24.0" %}
{% set sha256 = "83ec8d9a5827ee44bb1c0601a63696a8a9086beaf0151c8255556299246081bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: python setup.py build build_ext -I${PREFIX}/include -L${PREFIX}/lib install --single-version-externally-managed --record record.txt  # [not win]
  script: python setup.py install --no-cython --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
    - libev  # [not win]

  run:
    - python
    - numpy
    - six >=1.9
    - geomet >=0.1,<0.3

test:
  requires:
    - pip
  imports:
    - cassandra
    - cassandra.cqlengine
    - cassandra.io
    - cassandra.numpy_parser  # [not win and python_impl == 'cpython']
  commands:
    - pip check

about:
  home: http://github.com/datastax/python-driver
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python driver for Cassandra
  description: |
    A modern, feature-rich and highly-tunable Python client library for Apache Cassandra (2.1+)
    using exclusively Cassandra’s binary protocol and Cassandra Query Language v3.
  doc_url: http://datastax.github.io/python-driver/api/index.html
  dev_url: http://github.com/datastax/python-driver

extra:
  recipe-maintainers:
    - petercable
    - anirrudh
    - scopatz
    - xylar
