# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "mZm4/OTMxzxdv9BBpqH1TkQdy04H3BunHLUA77GZk5+DVjcVzWuGgyzNviR94qvRug/uggQpTOJX/FpmY46UFmRloW/H9OJQfYerdlorwMFEVi3JS/JTuQQXItlZV35kwfRuOB2Q6Q+3NkTkMFyX3lpXWuONF62+j0mI5RJGCs20ExywIEdtPlcsBbS7f1LBIF7Mbdao7uL7Q9vHVHj33lrEP6t7VjrXUTt8NWbsNJPv0RjEqtmcOVukHX1dJW3+2mf9ksp8us1cpb04MO3slQ5aNkjOuKrvyqPFyWpBiw8v78KX2/cBDqPIZoagXYo4AqM5NAqy2MOp3NlZX3SyfsY//zuvei/RXHwt40R2dnOsIvJnJhlcqK5BPRjVIxnzvxLXUmRGPt0gq3/OEbL/8fQOOJljpoqhCk9P4EoDwNXWyqOx49rXZ/L/IiBZtKTEKzLAQywJzqQ98YlEDr9mQRxS/Y6q3P0ExpDuqEDmZ3Wq4coQloKfBXe0puZuaXuRTeW4aG+KGkNwDxyM8Z7MODsKzdePgW4/M8RXbEYwpURexwVw+igrftmbC1SvAnkO/vHUfDX3PxHZNQBZbgIf8xMrvLUlI8ry5EhvomP7Oew7uZ6LXMNlFVdzoRoo6nVHmxMflbhp5Uq4ppfVEF8N9Y7gbfY1eposHStqGSq5U4w="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml