appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mZm4/OTMxzxdv9BBpqH1TkQdy04H3BunHLUA77GZk5+DVjcVzWuGgyzNviR94qvRug/uggQpTOJX/FpmY46UFmRloW/H9OJQfYerdlorwMFEVi3JS/JTuQQXItlZV35kwfRuOB2Q6Q+3NkTkMFyX3lpXWuONF62+j0mI5RJGCs20ExywIEdtPlcsBbS7f1LBIF7Mbdao7uL7Q9vHVHj33lrEP6t7VjrXUTt8NWbsNJPv0RjEqtmcOVukHX1dJW3+2mf9ksp8us1cpb04MO3slQ5aNkjOuKrvyqPFyWpBiw8v78KX2/cBDqPIZoagXYo4AqM5NAqy2MOp3NlZX3SyfsY//zuvei/RXHwt40R2dnOsIvJnJhlcqK5BPRjVIxnzvxLXUmRGPt0gq3/OEbL/8fQOOJljpoqhCk9P4EoDwNXWyqOx49rXZ/L/IiBZtKTEKzLAQywJzqQ98YlEDr9mQRxS/Y6q3P0ExpDuqEDmZ3Wq4coQloKfBXe0puZuaXuRTeW4aG+KGkNwDxyM8Z7MODsKzdePgW4/M8RXbEYwpURexwVw+igrftmbC1SvAnkO/vHUfDX3PxHZNQBZbgIf8xMrvLUlI8ry5EhvomP7Oew7uZ6LXMNlFVdzoRoo6nVHmxMflbhp5Uq4ppfVEF8N9Y7gbfY1eposHStqGSq5U4w=}
